/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Jawaban;
import View.HighScore;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author VESHEA GO
 */
public class Play extends javax.swing.JFrame {

//    String jawaban[] = {"kambing_guling", "mari_makan", "minta_uang", "tuang_air", "untaian_bunga",};
    byte kesempatan = 3;
//    byte posisi = 0;
    int score = 0;
//    String nama = null;
//    String temp;
//    private Pemain Pemain;
//    private Jawaban Jawaban;
//
//    Jawaban jb = new Jawaban();

    public Play() {
        initComponents();
//        jb.sortingJawaban(jawaban);
//        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblKesempatan = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJawaban = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/100.png"))); // NOI18N

        lblKesempatan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblKesempatan.setForeground(new java.awt.Color(241, 196, 15));
        lblKesempatan.setText("3");

        lblScore.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblScore.setForeground(new java.awt.Color(241, 196, 15));
        lblScore.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 196, 15));
        jLabel5.setText("Jawaban : ");

        txtJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJawabanActionPerformed(evt);
            }
        });

        btnCek.setText("CEK");
        btnCek.setPreferredSize(new java.awt.Dimension(79, 30));
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kambing_guling.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 196, 15));
        jLabel2.setText("KESEMPATAN :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 196, 15));
        jLabel3.setText("SCORE :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblScore))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKesempatan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(gambar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKesempatan)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(gambar)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
//        String jwb = txtJawaban.getText().replace(" ", "_");

//
//        if (jwb.equalsIgnoreCase("")) {
//            JOptionPane.showMessageDialog(this, "JAWABAN BELUM DIISI");
//            txtJawaban.requestFocus();
//        } else {
//            if (jwb.equalsIgnoreCase(jawaban[posisi])) {
//                JOptionPane.showMessageDialog(this, "HORE! JAWABAN ANDA BENAR");
//                txtJawaban.requestFocus();
//                posisi++;
//                score += 20;
//                lblScore.setText("Score : " + score);
//                txtJawaban.setText("");
//            } else {
//                JOptionPane.showMessageDialog(this, "MAAF, JAWABAN ANDA SALAH");
//                kesempatan--;
//                txtJawaban.requestFocus();
//                lblKesempatan.setText("Kesempatan : " + kesempatan);
//            }
//        }
//
//        if (kesempatan == 0) {
//            JOptionPane.showMessageDialog(this, "KALAH");
//            JOptionPane.showMessageDialog(this, "SKOR ANDA = " + score);
//            nama = JOptionPane.showInputDialog("Nama Anda");
//            Pemain p = new Pemain();
//            p.setScore(score);
//            p.setNama(nama);
//            new HighScore().setVisible(true);
//            this.dispose();
//        }
//
//        if (posisi > jawaban.length - 1) {
//            JOptionPane.showMessageDialog(this, "SELAMAT ANDA MENANG");
//            JOptionPane.showMessageDialog(this, "SCORE ANDA = " + score);
//            nama = JOptionPane.showInputDialog("Nama Anda");
//            Pemain p = new Pemain();
//            p.setScore(score);
//            p.setNama(nama);
//            new HighScore().setVisible(true);
//            this.dispose();
//        } else {
//            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/" + jawaban[posisi] + ".png")));
//        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void txtJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJawabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJawabanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKesempatan;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextField txtJawaban;
    // End of variables declaration//GEN-END:variables

//    public JButton getBtnCek(){
//        return btnCek;
//    }
//    
//    public String getJawaban(){
//        return txtJawaban.getText();
//    }
//    
//    public void setJawaban(String jawaban){
//        txtJawaban.setText(jawaban);
//    }
//    
//    public void addActionListener(ActionListener e){
//        btnCek.addActionListener(e);
//    }
//
//    public JLabel getLblKesempatan() {
//        return lblKesempatan;
//    }
//
////    public void setLblKesempatan(JLabel lblKesempatan) {
////        this.lblKesempatan = lblKesempatan;
////    }
//
//    public JLabel getLblScore() {
//        return lblScore;
//    }
////
////    public void setLblScore(JLabel lblScore) {
////        this.lblScore = lblScore;
////    }
//
//    public void setLblScore(int score) {
//        this.score = score;
//    }
//
//    public void setLblKesempatan(byte kesempatan) {
//        this.kesempatan = kesempatan;
//    }
//    public void btnCekActionPerformed() {
//        
//        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/" + jawaban[posisi] + ".png")));
//    }
//    
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public JButton getBtnCek() {
        return btnCek;
    }

    public void setBtnCek(JButton btnCek) {
        this.btnCek = btnCek;
    }

    public JLabel getLblKesempatan() {
        return lblKesempatan;
    }

    public void setLblKesempatan(byte kesempatan) {
        lblKesempatan.setText(String.valueOf(kesempatan));
    }

    public JLabel getLblScore() {
        return lblScore;
    }

    public void setLblScore(int score) {
        lblScore.setText(String.valueOf(score));
    }

    public String getTxtJawaban() {
        return txtJawaban.getText();
    }

    public void setTxtJawaban(String x) {
        txtJawaban.setText(x);
    }

    public JLabel getGambar() {
        return gambar;
    }

    public void setGambar(JLabel gambar) {
        this.gambar = gambar;
    }

    public void nextGambar(byte posisi) {
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/" + posisi + ".png")));
    }
    
    public void addActionListener(ActionListener x){
        btnCek.addActionListener(x);
    }
}
